services:
  devcontainer:
    build:
      context: .devcontainer/
      dockerfile: Dockerfile.base
    volumes:
      - .:/workspace
    command: ./cloudflared tunnel  --config ./.cloudflared/config.yml  -origincert /workspace/.cloudflared/cert.pem run





